"""
Django settings for dmrc_core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
import pymysql
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Initialize PyMySQL to act as standard MySQLdb
pymysql.install_as_MySQLdb()

# Load environment variables from .env
load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# ENVIRONMENT
#
# Everything below can be set in .env. The defaults are chosen so that a
# developer needs no .env entries at all, while a deployed server gets the safe
# value automatically rather than relying on someone remembering to set it.
# ==============================================================================

def env_flag(name, default=False):
    """Read a true/false setting from the environment."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('true', '1', 'yes', 'on')


def env_list(name, default=()):
    """Read a comma-separated setting from the environment."""
    raw = os.environ.get(name)
    if raw is None:
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Is this a developer at a terminal, or a deployed server?
#
# The reliable difference is not a setting somebody remembers to change -- it is
# HOW the application was started. A developer runs `python manage.py runserver`;
# a deployed instance is served through wsgi.py by Gunicorn or uWSGI, which never
# touches manage.py.
#
# So DEBUG is on by default for the former and off for the latter. The failure
# modes then land the right way round: forget to configure something locally and
# nothing happens, forget it in production and the server refuses to start and
# says why. Setting DEBUG explicitly in .env overrides this either way.
#
# DEPLOYMENT NOTE: set DEBUG=False explicitly in .env on any server. Without it,
# anyone who starts this with `manage.py runserver` -- to smoke-test the install,
# say -- silently turns DEBUG back on, which disables both production checks at
# the end of this file and re-enables the development identity provider.
RUNNING_VIA_MANAGE_PY = os.path.basename(sys.argv[0] or '') == 'manage.py'

DEBUG = env_flag('DEBUG', default=RUNNING_VIA_MANAGE_PY)

# SECURITY WARNING: keep the secret key used in production secret!
#
# Read from the environment. It used to be a literal here, while .env.example
# asked the IT team to set SECRET_KEY -- so the value they set was ignored and
# the development key went on being used, silently. It signs session cookies and
# the document viewer links, so a known key means those can be forged. The
# production check at the end of this file refuses to start if it is still this
# default.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-(z$dz%zdmck_8ltehhrde3fjjme&wk0pgd3bz7&_1kt+xa9$q4'
)

# Comma-separated, e.g. ALLOWED_HOSTS=portal.dmrc.org,10.20.30.40
# Django ignores this entirely while DEBUG is on, so the localhost defaults are
# only ever used in development.
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dmrc_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dmrc_core.wsgi.application'


# ==============================================================================
# DATABASE
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# TRANSPORT SECURITY
#
# TiDB Cloud, used during development, requires an encrypted connection and a CA
# bundle. A MySQL server on an internal network frequently requires neither. This
# used to be hardcoded -- an encrypted connection using a CA file at
# /etc/ssl/cert.pem for any host that was not exactly 'localhost' -- with no way
# to change it from .env. That path is the macOS one; on Linux the bundle is
# usually /etc/ssl/certs/ca-certificates.crt, so as written it could not connect
# on a deployed server at all.
#
# It is now configuration:
#
#   DB_SSL=False                 plain connection (typical for internal MySQL)
#   DB_SSL=True                  encrypted, using DB_SSL_CA below
#   DB_SSL_CA=/path/to/ca.pem    Linux:  /etc/ssl/certs/ca-certificates.crt
#                                macOS:  /etc/ssl/cert.pem
#
# The DEFAULT preserves the previous behaviour -- encryption for any host that is
# not local -- so nothing changes for an existing development setup. A local host
# now also covers 127.0.0.1 and an unset DB_HOST, which previously fell through
# to requiring TLS against a server that was unlikely to offer it.
# ==============================================================================

DB_HOST = os.environ.get('DB_HOST', '')

_DB_HOST_IS_LOCAL = DB_HOST.strip().lower() in ('localhost', '127.0.0.1', '::1', '')

DB_SSL = env_flag('DB_SSL', default=not _DB_HOST_IS_LOCAL)

# Path to the CA bundle used to verify the database server's certificate. Only
# read when DB_SSL is on. Left empty, the connection is encrypted without
# verifying the server certificate -- acceptable on a closed internal network,
# not on anything else.
DB_SSL_CA = os.environ.get('DB_SSL_CA', '/etc/ssl/cert.pem').strip()

DB_OPTIONS = {}
if DB_SSL:
    DB_OPTIONS['ssl'] = {'ca': DB_SSL_CA} if DB_SSL_CA else {'ssl': True}

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD':  os.environ.get('DB_PASSWORD'),
        'HOST': DB_HOST,
        'PORT': os.environ.get('DB_PORT', '4000'),
        'OPTIONS': DB_OPTIONS,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Where `manage.py collectstatic` gathers static files for a web server to
# serve. Without this set, that command fails outright once DEBUG is off. The
# two portals are served as plain files by the web server and do not depend on
# it; it exists so a standard deployment step does not error.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The portals are served as static pages, so their requests are cross-origin.
#
# Allowing every origin is fine on a laptop and wrong on a network: it lets any
# website an employee happens to visit call this API as them. In production set
# CORS_ALLOW_ALL_ORIGINS=False and list the portal's own address in
# CORS_ALLOWED_ORIGINS.
#
# If the web server serves the portal pages and forwards /api/ to this
# application from the SAME address, the requests are no longer cross-origin and
# neither setting applies. That is the simpler arrangement and the recommended
# one.
CORS_ALLOW_ALL_ORIGINS = env_flag('CORS_ALLOW_ALL_ORIGINS', default=DEBUG)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')

# The identity header is a custom header, so browsers send a CORS preflight for
# it. django-cors-headers only permits headers on its default allow-list, so it
# must be declared here or the browser blocks the request before it reaches
# Django. Harmless to keep on the intranet, where identity comes from the
# session rather than this header.
CORS_ALLOW_HEADERS = [*default_headers, 'x-dmrc-employee']

# ==============================================================================
# IDENTITY INTEGRATION
#
# This portal does not authenticate anyone. Identity comes from DMRC's employee
# login system; the portal only decides what an identified employee may do.
#
# DMRC IT: implement portal/identity/intranet.py, then change the line below to
#     IDENTITY_PROVIDER = 'portal.identity.intranet.IntranetIdentityProvider'
# That single change is the whole integration. See portal/identity/base.py.
# ==============================================================================
# Settable from .env so the switch to the intranet is a configuration change
# rather than a source edit:
#     IDENTITY_PROVIDER=portal.identity.intranet.IntranetIdentityProvider
IDENTITY_PROVIDER = os.environ.get(
    'IDENTITY_PROVIDER', 'portal.identity.dev.DevIdentityProvider'
)

# Development only. Used when a request carries no X-DMRC-Employee header, so
# the portal still resolves to a usable identity during local work. Ignored
# entirely once IDENTITY_PROVIDER points at the intranet implementation.
#
# An ORDINARY EMPLOYEE, deliberately -- not the SYS-ADMIN.
#
# This is the identity anything without a header falls back to: a curl request,
# the address bar, a page whose script failed to load. Defaulting that to a
# SYS-ADMIN meant the most privileged account in the portal was also the one
# handed out when nobody said who they were.
#
# It also made the referral portal misrepresent itself. That portal is for
# ordinary staff referring candidates, and EMP-4471 is seeded precisely as the
# employee with no dashboard account at all -- so the default now matches what
# the portal is for, and a referral submitted without an explicit identity is
# filed against a plausible referrer rather than against the administrator.
DEV_DEFAULT_EMPLOYEE_CODE = 'EMP-4471'

# --- DOCUMENT STORAGE CONFIGURATION ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# PROTECTED DOCUMENT STORAGE
#
# Documents uploaded by referrers (Aadhaar, photograph, LOR and anything else an
# administrator configures) are stored HERE, deliberately OUTSIDE MEDIA_ROOT, so
# Django's static file handler never serves them. They are reachable only
# through the authenticated viewer endpoint, which checks the caller's role,
# streams the file inline, and records every access in the audit ledger.
#
# Before this, every uploaded document sat under /media/ and could be fetched by
# anyone who knew or guessed a URL, with no login required at all.
#
# System-GENERATED documents (offer letters, certificates) stay in MEDIA_ROOT:
# they are meant to be circulated, printed and emailed.
# ==============================================================================
PROTECTED_DOCUMENT_ROOT = BASE_DIR / 'protected_documents'

# How long a document view link stays valid. Short by design: a link copied out
# of the page stops working quickly, which limits casual sharing.
DOCUMENT_LINK_TTL_SECONDS = 600

# Superseded documents are moved here when a newer version replaces them.
# This directory is deliberately OUTSIDE MEDIA_ROOT and is never served by
# Django, so quarantined files are unreachable by URL and invisible to every
# role, while remaining recoverable by a system administrator. Apply the
# organisation's records-retention policy to this directory.
QUARANTINE_ROOT = BASE_DIR / 'quarantine'

# ==============================================================================
# SIGNATURE STORAGE
#
# An HR-APP's signature image, stamped onto every offer letter they issue.
#
# OUTSIDE MEDIA_ROOT, and more strictly protected than anything else here: a
# signature is the one file in this system whose theft lets somebody forge a
# DMRC document.
#
# It is never reachable by URL and never passes through the ordinary document
# viewer. One endpoint serves it -- /api/signatures/image/ -- and only to two
# people: the officer it belongs to, and a SYS-ADMIN, who has to see it to
# decide on it. Every other access is a read from disk while drawing a letter.
#
# Layout:
#   signatures/active/<user_id>.png    the signature currently in force
#   signatures/pending/<user_id>.png   uploaded, awaiting SYS-ADMIN approval
#
# Rejected and replaced signatures are moved into QUARANTINE_ROOT, so an
# officer's previous signature stays recoverable without being reachable.
# ==============================================================================
SIGNATURE_ROOT = BASE_DIR / 'signatures'

# Signature images only. Deliberately narrow: a PDF or an SVG can carry a script
# or an external reference, and this file is opened by the document generator.
SIGNATURE_ALLOWED_EXTENSIONS = ('.png', '.jpg', '.jpeg')
SIGNATURE_MAX_SIZE_MB = 2

# ==============================================================================
# GENERATED DOCUMENT STORAGE
#
# Offer letters and completion certificates produced by the portal.
#
# These used to be destined for MEDIA_ROOT on the reasoning that they are meant
# to be circulated. That was wrong for two reasons:
#
#   1. Django only serves MEDIA_ROOT while DEBUG is on -- see dmrc_core/urls.py.
#      On the intranet DEBUG is off, so every one of those links would 404
#      unless somebody remembered to configure the web server. It would work
#      perfectly in development and fail silently in production.
#
#   2. An offer letter carries the candidate's name, college and joining date.
#      A link that needs no login is a link anyone can guess.
#
# So they live here, outside MEDIA_ROOT, and reach HR through the same audited,
# role-checked endpoint that already serves Aadhaar cards -- with download
# permitted, since HR-OPS must print the letter. Nothing for DMRC IT to
# configure, and nothing to forget.
#
# Candidates never need a link: the offer letter is handed over on paper.
# ==============================================================================
GENERATED_DOCUMENT_ROOT = BASE_DIR / 'generated_documents'

# ==============================================================================
# LOGGING
#
# With DEBUG off, an unhandled error returns a bare "Server Error (500)" to the
# user and the detail goes wherever the application server happens to send it --
# frequently nowhere anybody looks. The first production fault then arrives as
# "HR says the button does not work", with no trail behind it.
#
# So errors are written to a file as well as the console. The file rotates at
# 5 MB and keeps five old copies, which bounds disk use without anybody having
# to remember to prune it.
#
# LOG_DIR may be set in .env to point at a central location if DMRC has one.
# Whatever directory it names must be writable by the account running the
# application. Exclude it from version control.
# ==============================================================================
LOG_DIR = Path(os.environ.get('LOG_DIR') or (BASE_DIR / 'logs'))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'portal.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Unhandled exceptions in a view arrive here.
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Anything this project logs itself.
        'portal': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==============================================================================
# EMAIL
#
# EMAIL_MODE picks the backend. 'console' prints each message to the terminal
# and sends nothing; 'smtp' hands it to a real relay. Development defaults to
# console, a deployed server to smtp, so the whole notification flow can be
# built and tested with no mail server in existence.
#
# Nothing about DMRC's relay is hardcoded here. Switching to it is a .env
# change:
#     EMAIL_MODE=smtp
#     EMAIL_HOST=<relay hostname>
#     EMAIL_PORT=25
#     DEFAULT_FROM_EMAIL=<the address the relay permits>
# ==============================================================================

EMAIL_MODE = os.environ.get('EMAIL_MODE', 'console' if DEBUG else 'smtp').strip().lower()

if EMAIL_MODE == 'console':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT') or 25)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_flag('EMAIL_USE_TLS', default=False)
EMAIL_USE_SSL = env_flag('EMAIL_USE_SSL', default=False)

# Seconds to wait for the relay. Without this the default is no timeout, and an
# internal-only relay unreachable from where this runs would hang the send
# command indefinitely rather than recording a Failed row.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT') or 20)

# The From address. Left as a placeholder in development because the console
# backend does not care; the production check below refuses to start without a
# real one, since a relay that permits only certain From addresses will
# otherwise reject every message at send time.
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '').strip() or 'portal@localhost.invalid'

# How many Pending rows one run of `manage.py send_notifications` will attempt.
# Bounded so a cron run cannot occupy the relay indefinitely.
NOTIFICATION_SEND_BATCH_SIZE = int(os.environ.get('NOTIFICATION_SEND_BATCH_SIZE') or 50)

# ==============================================================================
# PRODUCTION SAFETY CHECKS
#
# Both of the mistakes below would be invisible until somebody exploited them,
# so they are made noisy instead: the server refuses to start rather than run
# insecurely, and says exactly what to change.
#
# Neither check does anything while DEBUG is on, so development is unaffected.
# ==============================================================================
if not DEBUG:
    from django.core.exceptions import ImproperlyConfigured

    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            "SECRET_KEY is still the development key shipped with this project. "
            "Set SECRET_KEY in .env to a freshly generated 50-character random "
            "string. It signs session cookies and document viewer links, so a "
            "key that has been published means both can be forged.\n\n"
            "Generate one with:\n"
            "  python -c \"from django.core.management.utils import "
            "get_random_secret_key; print(get_random_secret_key())\""
        )

    if IDENTITY_PROVIDER.endswith('DevIdentityProvider'):
        raise ImproperlyConfigured(
            "IDENTITY_PROVIDER is still the DEVELOPMENT provider, which trusts "
            "an X-DMRC-Employee request header -- anyone able to reach this "
            "server could impersonate any employee, including a SYS-ADMIN.\n\n"
            "Implement portal/identity/intranet.py and set in .env:\n"
            "  IDENTITY_PROVIDER=portal.identity.intranet.IntranetIdentityProvider\n\n"
            "See portal/identity/base.py for the contract -- it is one method."
        )

    if EMAIL_MODE != 'smtp':
        raise ImproperlyConfigured(
            "EMAIL_MODE is not 'smtp', so notifications would be printed to the "
            "console and never sent, while the portal recorded them as Sent.\n\n"
            "Set in .env:\n"
            "  EMAIL_MODE=smtp"
        )

    if not EMAIL_HOST:
        raise ImproperlyConfigured(
            "EMAIL_HOST is not set. Set the relay hostname in .env, e.g.\n"
            "  EMAIL_HOST=smtp.dmrc.org"
        )

    if DEFAULT_FROM_EMAIL == 'portal@localhost.invalid':
        raise ImproperlyConfigured(
            "DEFAULT_FROM_EMAIL is still the development placeholder. Set it in "
            ".env to the address DMRC's relay permits this application to send "
            "as. A relay that restricts From addresses will reject every "
            "message otherwise."
        )

    if EMAIL_USE_TLS and EMAIL_USE_SSL:
        raise ImproperlyConfigured(
            "EMAIL_USE_TLS and EMAIL_USE_SSL are both on. They are mutually "
            "exclusive -- TLS is STARTTLS on port 587, SSL is implicit TLS on "
            "port 465. Turn one off in .env."
        )

    # Standard hardening once the portal is behind HTTPS. Set SECURE_COOKIES=False
    # if TLS terminates elsewhere and the portal itself is reached over plain
    # HTTP, otherwise sessions will not work.
    SESSION_COOKIE_SECURE = env_flag('SECURE_COOKIES', default=True)
    CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'