# Generated by Django 4.2.30 on 2026-08-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('academic_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=200)),
                ('degree_program', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('current_semester', models.CharField(max_length=20)),
                ('grading_system', models.CharField(max_length=10)),
                ('current_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'academic_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dmrc_reference_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('referral_source', models.CharField(max_length=13)),
                ('referrer_notification_email', models.CharField(blank=True, max_length=150, null=True)),
                ('duration_weeks', models.IntegerField()),
                ('is_ward', models.IntegerField(blank=True, null=True)),
                ('accepted_declarations', models.IntegerField(blank=True, null=True)),
                ('form_correction_remarks', models.TextField(blank=True, null=True)),
                ('rejection_category', models.CharField(blank=True, max_length=16, null=True)),
                ('approval_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_admin_escalated', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('is_waitlisted', models.IntegerField(blank=True, null=True)),
                ('is_no_show', models.IntegerField(blank=True, null=True)),
                ('is_resubmitted', models.IntegerField(blank=True, null=True)),
                ('doj_reschedule_expires_at', models.DateTimeField(blank=True, null=True)),
                ('doj_reschedules_count', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=25)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_status_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivedAcademicDetails',
            fields=[
                ('archive_academic_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_application_id', models.IntegerField()),
                ('university_name', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=200)),
                ('degree_program', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('current_semester', models.CharField(max_length=20)),
                ('grading_system', models.CharField(max_length=20)),
                ('current_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'archived_academic_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivedApplications',
            fields=[
                ('archive_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_application_id', models.IntegerField()),
                ('application_code', models.CharField(blank=True, max_length=50, null=True)),
                ('dmrc_reference_code', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.CharField(max_length=150)),
                ('student_mobile', models.CharField(max_length=20)),
                ('student_aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('college_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=100)),
                ('grading_system', models.CharField(max_length=20)),
                ('current_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department_name', models.CharField(max_length=100)),
                ('allotted_sub_department', models.CharField(blank=True, max_length=100, null=True)),
                ('session_term', models.CharField(max_length=20)),
                ('application_year', models.IntegerField()),
                ('duration_weeks', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('is_waitlisted', models.IntegerField(blank=True, null=True)),
                ('is_no_show', models.IntegerField(blank=True, null=True)),
                ('is_employee_ward', models.IntegerField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=50, null=True)),
                ('referrer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('referrer_employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('referrer_notification_email', models.CharField(blank=True, max_length=150, null=True)),
                ('actual_date_of_joining', models.DateField(blank=True, null=True)),
                ('dmra_session_date', models.DateField(blank=True, null=True)),
                ('dmra_attended', models.IntegerField(blank=True, null=True)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
                ('rejection_category', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_admin_escalated', models.IntegerField(blank=True, null=True)),
                ('is_resubmitted', models.IntegerField(blank=True, null=True)),
                ('doj_reschedule_expires_at', models.DateTimeField(blank=True, null=True)),
                ('doj_reschedules_count', models.IntegerField()),
                ('archived_year', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archived_applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivedDocuments',
            fields=[
                ('archive_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_application_id', models.IntegerField()),
                ('doc_type_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('is_manually_overridden', models.IntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'archived_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeReferralDrafts',
            fields=[
                ('draft_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=20)),
                ('personal_email', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('allotted_doj', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('doj_reschedules_count', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'college_referral_drafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CycleDepartmentCapacities',
            fields=[
                ('capacity_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_capacity', models.IntegerField()),
                ('seats_occupied', models.IntegerField()),
            ],
            options={
                'db_table': 'cycle_department_capacities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CycleDocumentRequirements',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_mandatory', models.IntegerField(blank=True, null=True)),
                ('required_at', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'cycle_document_requirements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CycleJoiningDates',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('allowed_doj', models.DateField()),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycle_joining_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CycleSubDepartments',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycle_sub_departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('is_manually_overridden', models.IntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=8, null=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('doc_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('allowed_extensions', models.CharField(blank=True, max_length=100, null=True)),
                ('max_size_mb', models.IntegerField(blank=True, null=True)),
                ('is_system_generated', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('official_email', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternshipCycles',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_term', models.CharField(max_length=6)),
                ('application_year', models.IntegerField()),
                ('application_start_date', models.DateField()),
                ('application_end_date', models.DateField()),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internship_cycles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JoiningDetails',
            fields=[
                ('joining_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_doj', models.DateField()),
                ('allotted_date_of_joining', models.DateField(blank=True, null=True)),
                ('reporting_time', models.TimeField(blank=True, null=True)),
                ('assigned_room_location', models.CharField(blank=True, max_length=100, null=True)),
                ('documents_to_carry', models.TextField(blank=True, null=True)),
                ('actual_date_of_joining', models.DateField(blank=True, null=True)),
                ('dmra_session_date', models.DateField(blank=True, null=True)),
                ('dmra_attended', models.IntegerField(blank=True, null=True)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'joining_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=29)),
                ('recipient_email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(blank=True, max_length=7, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('permissions_level', models.IntegerField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('fathers_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('personal_email', models.CharField(max_length=150)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('permanent_address', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubDepartments',
            fields=[
                ('sub_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_department_name', models.CharField(max_length=100, unique=True)),
                ('is_global_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLogs',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
                ('action_type', models.CharField(max_length=100)),
                ('target_entity_type', models.CharField(max_length=50)),
                ('target_entity_id', models.IntegerField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('active_signature_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pending_signature_path', models.CharField(blank=True, max_length=500, null=True)),
                ('signature_approval_status', models.CharField(blank=True, max_length=8, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
